### ISSUE TITLE
How can we add "pulsar-2" to Keplr wallet?

### ISSUE THREAD

**Issue by korzewski** [scrtlabs/api-registry#3]
Hi @assafmo,
I can see you have added info about `pulsar-2` yesterday - https://github.com/scrtlabs/testnet/blob/master/pulsar-2/details.md?plain=1#L10

This seems to be a new testnet for Secret network, linked with official faucet https://faucet.secrettestnet.io/
Could you please provide there some instructions how we can add this network to Keplr wallet?

**Comment by assafmo** [comment]
Hi, take a look at this:

https://github.com/scrtlabs/QueryBalancePermitDemo/blob/d48a1c893eb042329f14518084b6d887ee2c0ea2/src/KeplrStuff.tsx#L70

**Comment by korzewski** [comment]
Hi, Thanks for that!

I have found this link https://tools.trivium.network/addtestnets/
This one provides all network config, required for `pulsar-2`
